sudo: required
services:
  - docker

before_install:
  - docker build -t neekhil18/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true neekhil18/docker-react npm run test -- --coverage
